
name: Build Homebrew

on: [push,workflow_dispatch]
jobs:
  build:

    runs-on: ubuntu-latest
    container:
      image: d3fau4/nx-dev:latest
    steps:
    - uses: actions/checkout@v1
    - name: Update repo.
      run: |
        git submodule update --init --recursive
        
    - name: Make app
      continue-on-error: true
      run: |
        make -j$(nproc) -C nspmini
        make -j$(nproc)
        sudo chmod 0777 * -R
        sudo chmod 0755 RipJKForwader/BuildTools/hacbrewpack
        make -j$(nproc) NSP
        
    - uses: actions/upload-artifact@master
      with:
        name: Homebrew
        path: out/*
